// 3業種の設定
export const INDUSTRIES = {
  hair: {
    id:          'hair',
    name:        'Hair Passport',
    sub:         'あなたの髪のパスポート',
    color:       '#e8a0b0',
    colorDeep:   '#c4687e',
    colorLight:  '#f7e8ed',
    colorPale:   '#fdf1f4',
    colorBorder: '#f0d0da',
    bg:          '#fdf8f8',
    menus: ['カット','カラー','ブリーチ','パーマ','縮毛矯正','トリートメント','ヘッドスパ','インナーカラー'],
    salonLabel:  '店名',
    memoPlaceholder: '根元・毛先の状態、使用薬剤、次回の提案など',
  },
  nail: {
    id:          'nail',
    name:        'Nail Passport',
    sub:         'あなたのネイルのパスポート',
    color:       '#a8c4e8',
    colorDeep:   '#5a8abf',
    colorLight:  '#e0ecf8',
    colorPale:   '#f0f6fd',
    colorBorder: '#c8ddf0',
    bg:          '#f6f9fd',
    menus: ['ジェルネイル','スカルプ','ネイルケア','ネイルアート','オフ','パラジェル','フィルイン','ハンドケア'],
    salonLabel:  'サロン名',
    memoPlaceholder: 'カラー番号・サイズ・アート内容、次回の提案など',
  },
  lash: {
    id:          'lash',
    name:        'Lash Passport',
    sub:         'あなたのまつ毛のパスポート',
    color:       '#b8a8d4',
    colorDeep:   '#7a5abf',
    colorLight:  '#e8e0f5',
    colorPale:   '#f5f0fd',
    colorBorder: '#d8c8f0',
    bg:          '#f9f6fd',
    menus: ['シングル','ボリュームラッシュ','フラットラッシュ','MIXラッシュ','オフ','コーティング','まつ毛パーマ','リペア'],
    salonLabel:  'サロン名',
    memoPlaceholder: 'カール・本数・長さ・グルー情報、次回の提案など',
  },
}
